# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
  [build]
  install = "yarn; yarn bootstrap"
  command = "yarn auth:build"
  functions = "out_functions"
  publish   = "out_publish"
#  ignore = "git diff --quiet HEAD^ HEAD packages/*"

  [[ plugins ]]
  package = "@netlify/plugin-nextjs"
