# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
  [build]
  command = "yarn auth:start"
  functions = "out_functions"
  publish   = "out_publish"
#  ignore = "git diff --quiet HEAD^ HEAD packages/*"
#  [[ plugins ]]
#  package = "@netlify/plugin-nextjs"
