# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
  [build]
  base = "./"
  install = "yarn; yarn bootstrap"
  command = "yarn auth:build"
  publish = "packages/auth/.next"
#  ignore = "git diff --quiet HEAD^ HEAD packages/*"

  [[ plugins ]]
  package = "@netlify/plugin-nextjs"
