# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
  [build]
  base = "/"
  command = "yarn auth:start"
  publish = "packages/auth"
  functions = ".netlify/functions"
#  ignore = "git diff --quiet HEAD^ HEAD packages/*"
#  [[ plugins ]]
#  package = "@netlify/plugin-nextjs"
